risudo/minishell

includes/parse.h
srcs/check_syntax.c
srcs/execdata_utils.c
srcs/parse_cmd.c
srcs/parse_cmd_utils1.c

以下のシンタックスエラーはエラーメッセージ吐いてNULLを返すようにしました。
- クォーテーションが閉じられていない
- パイプで終わっている
- リダイレクトの記号が連続している

シンタックスチェック

---

includes/execute.h
includes/minishell.h
rakiyama/for_running_and_utils.c
rakiyama/run.sh
srcs/command.c
srcs/env_functions.c
srcs/execute_setdata.c
srcs/execute_start.c
srcs/execute_utils_libft.c
srcs/execute_utils_list.c
srcs/execute_utils_wrapper.c
srcs/wrapper2.c

#18 
- enum e_~ → t_~
- 標準ライブラリのincludeを追加
- execdataのメンバーに下記追加
- ori_stdin
- ori_stdout
- ori_stderr
in_fd,out_fdは消す予定なのでそれは後で話しましょう。
- rakiyama.h→execute.h
- ファイル名変更(ft_getenvはenv_functions.cに入ります）
- 関数名変更
- コメントの追加
- echoで出力ごとに空白を入れる
- srcs/execute_start.c内に下記追加
- enumの追加
stdfd_handler()で使う、ひとまずこのファイル内で定義
- stdfd_handler()の追加
標準入出力の保存・回復で使います

ヘッダーとファイル、関数名などの整理

---

srcs/check_syntax.c
srcs/expansion_utils2.c
srcs/parse_cmd.c
test/result.txt

#20 
`is_delimiter`を修正して、数字、アルファベット、アンダーバー以外の文字を区切り文字と認識するようにしました。
test/result.txtの315行目〜354行目でテスト結果が出力してあります。

fix: is_dilimiter

---

includes/execute.h
rakiyama/for_running_and_utils.c
rakiyama/run.sh
srcs/execution_start.c
srcs/minishell_loop.c

#31 
- srcs/minishell_loop.cを作成、中のminishell_loop()にenvpを渡すと実行できます。
- rakiyamaディレクトリ内の変更は僕がテストするために動かしているので無視してください。
- srcs/execute_start.c内のexcute_loop()
- prev_pipe_read変数の追加
パイプで入出力を繋ぐ際に、標準入出力fdに変更を加えるのは子プロセスのみにして親で標準入出力を見失うなどの面倒な現象を防ぐようにしました。
- data->pipefdを無くし、関数何で宣言したpipefdを使うよう変更
上の変更を行っている内にpipefdを構造体で持っておく必要がなくなったので無くしました。
- dataリストのメンバー変数pipefdは無くす方向性で動いてます。(ヘッダーなどはいじってません)
- minishell_loopを実行するとminishellが始まるのですが、command not foundなどエラーを吐かせた後、一回分次のコマンド実行が無視されるという不具合があります。
- あと若干実行速度が遅いかもです。

minishellを動かすループ関数の作成

---

srcs/tokenize1.c

#35 
command文字列の後ろにスペースがあった場合、74行目のwhileで`cmd`ポインターを文字列の外まで進めてしまっていました。

catバグる問題修正

---

srcs/main.c

#36
Ctrl  + \ を押されたときの対応しました。
Ctrl + \ で送られるシグナルは`SIG_QUIT`でこれが来た場合はハンドラーに`SIG_IGN`をセットすることで無視しています。
こんな簡単なことでいいのかって感じがするんですけど、とりあえずシグナルについてはこのくらいしかやることが見つかりません。

fix : signal

---

srcs/expansion_cmdlist.c
srcs/parse_cmd.c
test/compile.sh
test/debug_parse.sh
test/result.txt

#50 
#48 
parse_cmd.cの`expansion`関数でserch_enviolistを呼び出さずに
iolistでは
- 変数展開
- クォーテーションの除去
- それに伴うリストの追加
をしていません。
expansion_cmdlist.cを修正して$単体のときに変数展開をしないようにしました。
「$単体」の判定の仕方ですが、$の次の文字が環境変数の区切り文字(アルファベット、数字、アンダーバー以外)だったときに「$単体」としています。 これに関して、issue #50  の方にbashで$の次に特殊文字が来た場合の挙動を載せているのですが、`$!`や`$#`などは意味は調べてないですが特有の挙動があるようです。今回、記載のない特殊文字は解釈しないので例えば
```
$ echo $!
```
はbashだと何も表示されないが、minishellは`$!`を表示するようになります。
これは問題ないという認識で大丈夫ですか？
result.txtも合わせて確認お願いします。(diffのほとんどがiolistでの環境変数で見づらいですが)

fix: expansion

---

includes/parse.h
srcs/expansion_cmdlist.c
srcs/expansion_utils2.c
test/debug_parse.sh
test/result.txt

#54 
主にexpansion_mcdlist.cの`serch_new_space_cmdlist`を変更しました。
valueの前にスペースがある場合に対応するためにif文で２つに分けました。1文字目がスペースだった場合にclist->strにはスペース以降の文字列を入れて再帰してます。
valueの後ろにスペースがある場合に対応するために`insert_new_cmdlist`で新しく作るリストのstrの長さが0だった場合に何もせずreturnするようにしました。
result.txtの401行目~430行目にテスト結果があります。
ちゃんとできてるか不安です。
```
ねこパンチ
(′ω'((⊂(`ω´∩) ポカポカ
```

前後にスペース含む環境変数対応

---

libft/ft_strlen.c
srcs/expansion_cmdlist.c
test/debug_parse.sh
test/result.txt

#55
`expansion_key_cmdlist()`で`clist->str`の先頭から変数展開後のvalueの後ろまでの長さを返すようにして、whileの中の`ft_strdoll()`ではそのポインタから探すようにしました。
`expansion_key_cmdlist()`内の`ft_strlen()`でvalueがNULLだったときにセグフォするのでft_strlenを変更しました。
以下のテストを追加しました。
- 環境変数の中に環境変数があった場合
- 展開しない環境変数の次に展開する環境変数があった場合

update: expansioin cmdlist

---

includes/execute.h
srcs/expansion_io_utils.c
srcs/expansion_iolist.c
srcs/setdata_heredoc_cmdtype.c

iolistの変数展開で、環境変数の中に環境変数があったときに展開しないようにしました。

Mod expandio

---

includes/execute.h
includes/struct.h
srcs/execution_start.c
srcs/execution_utils.c
srcs/setdata_cmdline_redirection.c
srcs/setdata_heredoc_cmdtype.c
srcs/wrapper2.c
srcs/wrapper3.c

何故か昨日の終了ステータスの変更も反映されてます。。
- xpipe->ft_pipe
- ft_dup2(xdup2削除)
- xdup->ft_dup
- 返り値の型が変更されている関数たちは、上記で変更した関数に合わせて返り値を返すように修正しました。
- execdataメンバー
pipefdを削除、ori_stdin系をstdfd[]として配列で管理（各要素はe_stdfd指定)
- open_fd_handler()->redirect_fd_handler()、リダイレクト時に動く関数
- FD_SPECIFIED->指定されたfdが標準入出力の保存fdと被りがないか確認
- FD_REDIRECTED->指定されたfdがリダイレクトされたので、開いているフラグを立てる
- ALL_CLOSE->あけたfdを閉じる
- ヘッダーの整理とファイルの整理

exitせずにエラー処理を行うべき関数を修正、ファイルを整理しました。

---

includes/execute.h
srcs/execution_start.c
srcs/setdata_cmdline_redirection.c
srcs/setdata_heredoc_cmdtype.c

#77 
- setdata_heredoc_cmdtype.c
- get_here_doc()->子プロセスを生成して、ヒアドキュメントをchild_get_here_doc()で受け取る
- get_here_doc()->child_get_here_doc()の終了ステータスを見て成功したか、してないか判断します
- child_get_here_doc()->(基本的に以前のget_here_doc()と変わらないが)lineがNULLの時(Ctrl + D)にexitさせずにbreakさせます=プログラム自体ではなく受け取りを終了させる。
- その他
minishell起動中、いくつかヒアドキュメントを受け取っている途中で中断された場合、それまでの開いたPIPEのfdを閉じなければなりません。
今までは各所で閉じていましたが、統一するためにclear_list系で閉じたいと思っています。
なので今回変更した中でhere_doc_fdを閉じる作業をコメントアウトしたり、here_doc_fdに-1を入れているのはそのためです。
- data->std[]、iolist->here_doc_fdの初期化。
- clear_list系でiolist->here_doc_fdを閉じる、data->cmdlineのfreeをする。

ヒアドキュメントを子プロセスで受け取ります。

---

Makefile
includes/execute.h
includes/struct.h
srcs/command_nonbuiltin.c
srcs/execution_start.c
srcs/setdata_cmdline_redirection.c
srcs/setdata_heredoc_cmdtype.c
srcs/wrapper3.c
srcs/wrapper4.c

#79 
ブランチの切り方変えてみたんですが、他のブランチのpushの反映されてるみたいです。。
実行権限のあるファイルが見つかるまでPATHからファイルを探す作業を追加しました。
- struct.h内、e_path_typeのIS_FILEをEXECUTABLEとUN_EXEUTABLEの二つに変更しました。
- 上記により、wrapper3.c内のft_stat()で、ファイルがあった場合にそれが実行ファイルなのかどうかまで返り値を分けることができます。
- 上記により、command_nonbuiltin.c内で出力するエラー文の(ファイルは存在するが実行権限がなかった場合の)条件分岐が増えたので、関数を増やしてまとめるようにしました。

実行ファイルの探し方を変えました。

---

Makefile
includes/execute.h
srcs/clear_list.c
srcs/command_builtin1.c
srcs/command_builtin2.c
srcs/command_builtin3.c
srcs/command_nonbuiltin.c
srcs/execdata.c
srcs/execdata_utils.c
srcs/execution_start.c
srcs/expansion_iolist.c
srcs/setdata_cmdline_redirection.c
srcs/wrapper2.c
srcs/wrapper3.c
srcs/wrapper4.c

- new_iolst()でhered_doc_fd = -1の初期化が二箇所あったので一つ消したのですが大丈夫ですか？
- new_execdata()でstdfdの初期化も追加
- clear_iolist()でlist→here_doc_fdをclose処理追加(-1ならxclose内で無視されます)
- clear_ececdata()でcmdlineのfreeを追加
- ワカモレでコンパイル対応できるようにMakefileを変更しました。
- setdata_cmdlien_redirection()でリダイレクション処理成功時の終了ステータス->0の作業を追加
- t_perrorとft_puterrorを作りエラー出力をまとめた

初期化作業とcler_list系の追加

---

srcs/command_builtin3.c

exit引数無しで、終了ステータスが直前のstatusになるように変更しました。

mod exit status

---

srcs/command_nonbuiltin.c

実行ファイル検索でstatがエラーを返した時、エラーの内容によって終了ステータスを変更するよう修正。(今までは無条件で127だった)
```
minishell$ /bin/no_such_file
minishell: /bin/no_such_file: No such file or directory
minishell$ echo $?
127
minishell$ /bin/ls/no_such_file
minishell: /bin/ls/no_such_file: Not a directory
minishell$ echo $?
126
```
no such file or directoryの時に127にして、それ以外は126にしました。
理由としてはパスの途中で権限が無かった際にもstatがエラーを出し、権限なしは終了ステータス126だからです。
今のところそこまで合わせられていればいいかなという見解ですが、どうですかね...?

実行ファイル検索でエラーが起きた際の終了ステータス変更

---

includes/execute.h
includes/struct.h
srcs/clear_list.c
srcs/delimit_fd.c
srcs/execdata.c
srcs/execdata_utils.c
srcs/execution_start.c
srcs/execution_utils.c
srcs/execution_utils_libft.c
srcs/setdata_cmdline_redirection.c
srcs/setdata_heredoc_cmdtype.c
srcs/wrapper2.c
srcs/wrapper3.c

- here_doc_fdをopen_fdと名前変更
- redirect処理後にopen_fdにリダイレクトしたfdを代入しておいて、clear_list.c内で閉じます
- redirect_fd_handler()の処理が入らなくなったので、resave_stdfd()という名前に変えてsaveされているstdfdとの被りだけ見てます
- xcloseをft_closeにしました

close all open_fd at clear_list.c

---

includes/execute.h
srcs/clear_list.c
srcs/command_builtin3.c
srcs/command_nonbuiltin.c
srcs/execution_start.c
srcs/setdata_heredoc_cmdtype.c
srcs/wrapper2.c
srcs/wrapper3.c

errnoの数値による条件分岐を定義されてるマクロに変更しました。
ft_closeをxcloseに戻し、errno == EBADF(fdが無効)な時はexitせず、それ以外のエラーはexitするようにしました。
fdが無効な時は開いているfdが放置されるわけではないので無視していいという考えです。
それ以外のエラーは対処の仕方がわからないのでexitさせるという考えです。
exitで引数がlongを超えたり数字出なかったりした場合に、manに従いexit status 2にしました。

mod errno=

---

includes/execute.h
srcs/execution_start.c
srcs/setdata_cmdline_redirection.c
srcs/wrapper3.c

ft_dup2()の引数にあった、エラー時exitをさせるフラグを無くして、単純に返り値を返すようにしました。
exitするかどうかは受け取り側で対処します。

mod ft_dup2()

---

includes/execute.h
srcs/execution_start.c
srcs/execution_utils.c
srcs/setdata_heredoc_cmdtype.c
test/test_main.c

- 子プロセス生成前にSIG_INT->IGN
- 子プロセスでSIG_INT->DFL
- 子プロセス終了後、親でSIG_INT->ハンドラー
- 子プロセス生成前にSIG_INT->IGN
- 子プロセスでSIG_INT->DFL,SIG_QUIT->DFL
- 子プロセス終了後、親でSIG_INT->ハンドラー
- 親プロセスで子プロセスの終了ステータスを拾う関数としてset_status_from_child_status()を追加

シグナルハンドラーを修正しました。

---

srcs/parse_tokenlist.c
srcs/tokenize1.c

close #106 
`tokenize_cmd_by_space()`で、commandがスペースだけだった場合は
```
if (init_vars(&cmd, &start, &flag_quot))
return (NULL);
```
でNULLを返すようにしました。
セグフォ対策を追加しました。

スペースだけの場合に対応しました

---

srcs/main.c
test/test_main.c

動作例。Ctrl+Dを押されたら、前回の終了ステータスでexitします。
```
bash-3.2 ./minishell
minishell$ jklfjsd
minishell: jklfjsd: command not found
minishell$ exit
[127] bash-3.2 ./minishell
minishell$ exit
bash-3.2 ./minishell
minishell$ <jfkdslj
minishell: jfkdslj: No such file or directory
minishell$ exit
[1] bash-3.2
```

Ctrl+Dでexitするように変更しました。

---

srcs/parse_tokenlist.c
srcs/tokenize2.c
srcs/tokenize_utils.c

```
> >a
```
と
```
>>a
```
の区別ができていませんでした。
test.shも通ってるのを確認しました。
```
minishell$ ls > >a
minishell: syntax error near unexpected token >
minishell$ ls > > a
minishell: syntax error near unexpected token >
minishell$ ls < < a
minishell: syntax error near unexpected token <
```
`static bool	is_delimiter_to_split(char *ptr, char *head)`のif文、吐きそうですね

`< <` がシンタックスエラーになってない問題修正

---

Makefile
includes/parse.h
srcs/execdata.c
srcs/parse_tokenlist.c
srcs/tokenize2.c
srcs/tokenize_utils.c

- srcs/execdata.cの22行目でfdとリダイレクトを区切っているのですが、<< と >>でも区切れるようにしました。
- `1>>`と`>>>`をシンタックスチェックで区別しないといけないのでis_syntax_error()を作りました。

support `1>>a`

---

Makefile
srcs/command_builtin1.c

下記で、fileに出力されずに標準出力に出力されてしまったので修正しました。
```
echo -n aaa >file
```
nオプションの際、改行コードが出力されないため"aaa"がバッファリングされたまま次の動作に入ってしまい、リダイレクト先に出力されない現象が起きたため、
printf()->ft_putstr_fd()に変更しました。

in:echo printf()->ft_putstr_fd()

---

includes/execute.h
srcs/command_builtin1.c
srcs/command_builtin2.c
srcs/command_builtin3.c
srcs/env_functions.c
srcs/main.c
test/files_for_test/test_main.c

以下で、data->elstを変更してもmain()のelstには反映されずenvlistの更新ができなかったので、
main()のwhile内でelstをdata->elstで更新するようにしました。
- unset、envlistの先頭ノードを消す
- export、envlistがNULLの時(env -i)、新しくノードを作成してもmain()のelstはNULLのまま
- main()、elstをdata->elstで更新
- ft_setenv()、listの先頭アドレスを返すようにしてlistがNULLでも、返り値で新ノードを追加できるようにした
- その他、ft_setenv()/ft_unsetenv()の呼び出し元ではdata->elstに返り値を受け取るようにした
->istのどこが変更されても更新できるように

envlist関連を変更しました。

---

includes/parse.h
srcs/expansion_cmdlist.c
srcs/expansion_utils1.c
test/cmdline.txt
test/error_cmdline.txt

`static size_t	search_new_space_cmdlist(t_cmdlist *clist, size_t idx)`を主に変更してます。
変数展開後のインデックス(expand_key_cmdlist()の返り値)を使って、どこまでが環境変数だったか判別できるようにしました。スペースで区切ってノードを追加していく処理の中で文字列のインデックスが環境変数だった場所を超えたらidxをSIZE_MAXにして処理を終了してます。
```
if (idx > i)
idx -= i;
else
idx = SIZE_MAX;
```
`test/cmdline.txt`の14~15行目でテストしてます。
分かりづらいと思うので一旦放置でも大丈夫です。

環境変数のあとのスペースが消されるやつ修正
