getcwd_chdir.c
=> getcwd_chdir.cを追加しました。

includes/minishell.h, srcs/wrapper1.c
=> fix wrapper.c

includes/minishell.h, srcs/execdata.c
=> delete in_fd out_fd in t_execdata

rakiyama/for_running_and_utils.c, rakiyama/put_info_func.c, rakiyama/run.sh, srcs/minishell_loop.c
minishell_loop()でft_callocを使うようにしました。
rakiyamaは無視してください。
=> minishell_loopを少し直しました。

includes/execute.h, srcs/command_builtin1.c, srcs/command_builtin2.c, srcs/command_builtin3.c, srcs/command_nonbuiltin.c, srcs/env_functions.c, srcs/execution_setdata.c, srcs/execution_start.c, srcs/execution_utils.c, srcs/execution_utils_list.c
#23 
- 各ファイルのコメントの追加
- 関数名変更、non_command()->no_command()
=> add comment

srcs/delimit_fd.c
=> add delimit_fd.c

includes/execute.h, srcs/execution_start.c, srcs/execution_utils.c, srcs/expansion_iolist.c, srcs/setdata_cmdline_redirection.c, srcs/setdata_heredoc_cmdtype.c, srcs/wrapper2.c, srcs/wrapper3.c
主に以下二つが肝です。
- リダイレクション対応関数
set_redirected_fd()
- 開いているfdを管理し、閉じる関数
open_fd_handler()
=> fd指定のリダイレクション対応と、開いたfdを全て閉じるよう修正。

includes/execute.h, srcs/execution_start.c, srcs/execution_utils.c, srcs/setdata_cmdline_redirection.c, srcs/setdata_heredoc_cmdtype.c, srcs/wrapper2.c, srcs/wrapper3.c
この前のプルリクでは開いているファイルディスクリプタをコマンド実行後に全て閉じるようにしていましたが、
その間ファイルディスクリプタの最大数を減らすことになり本家と異なるので、
いらないファイルディスクリプタは逐次閉じていくことにしました。
=> ファイルディスクリプタの閉じ方をそれぞれの関数で逐次閉じていくことにしました。

srcs/execution_utils_libft.c
#53 
ビルトインのexitで前後のis_spaceを飛ばすようにしました。
=> ft_atoll pass is_space

srcs/command_builtin2.c, srcs/execution_utils_libft.c
=> Mod export

includes/minishell.h, includes/parse.h, srcs/execdata.c, srcs/main.c, srcs/minishell_loop.c, srcs/parse_cmd.c, srcs/parse_tokenlist.c, srcs/tokenize1.c, test/parse_main.c, test/test_parse2.c
#69 
- parse_cmd 内の関数でstatusをグローバル変数に変更しました。
- プロンプトを緑にしました。
=> add : g_status

includes/struct.h, srcs/command_builtin1.c, srcs/command_builtin2.c, srcs/command_builtin3.c, srcs/command_nonbuiltin.c, srcs/execution_start.c, srcs/execution_utils_libft.c, srcs/minishell_loop.c, srcs/setdata_cmdline_redirection.c
#69 
基本的に全てグローバル変数に変更しただけです。
テスト結果
```
minishell > fjsldk
minishell: fjsldk: command not found
minishell > echo $?
127
minishell > >>>
minishell: syntax error near unexpected token >
minishell > echo $?
2
minishell > jfsdkl
minishell: jfsdkl: command not found
minishell > 
minishell > 
minishell > 
minishell > 
minishell > 
minishell > 
minishell > echo $?
127
minishell > ../private_minishell/
minishell: ../private_minishell/: is a directory
minishell > echo $?
127
minishell > 582394583>outfile
bad file descriptor
minishell > echo $?
1
minishell > export =fjskdl
minishell: export: =fjskdl: not a valid identifier
minishell > echo $?
1
minishell > exit 4324 43234
exit
minishell: exit: too many arguments
minishell > echo $?
1
minishell > exit 5823904852340598324
exit
bash-3.2$ echo $?
52
```
=> mod exit status

Makefile, includes/execute.h, includes/struct.h, srcs/command_builtin1.c, srcs/command_nonbuiltin.c, srcs/execution_start.c, srcs/setdata_cmdline_redirection.c, srcs/setdata_heredoc_cmdtype.c, srcs/wrapper3.c, srcs/wrapper4.c
ブランチの切り方変えてみたんですが、他のやつも反映されて出ちゃってます。。
srcs/command_builtin1.cだけ見てください。
bashに合わせて以下の条件でエラーを出します。
- STDOUT_FILENOが出力に使えるか(1<outfileは確かめる、2<outfileなどはエラー放置)
- echoとpwdだけ
=> 1<outfileでwrite error: bad file descriptorを出す。

srcs/main.c, test/leaks.sh
=> fix: leak envlist

test/leaks.sh
minishellを起動した後、別ターミナルでleaks.shを実行すると自動でリークチェックしてくれます。
リークスコマンドがエラーを吐かなければ何も表示されません。そのはず笑。
あとなんかGIFの動きが遅いっす笑
=> leaks.shに機能を追加

srcs/parse_tokenlist.c, test/parse/result.txt
close #90 
リダイレクトが連続したときにシンタックスエラー判定してなかったので修正しました。
=> fix: Consecutive redirect 

Makefile, includes/minishell.h, srcs/main.c, srcs/setdata_heredoc_cmdtype.c, srcs/signal_handler.c, srcs/tokenize1.c, test/cmdline.txt, test/test.sh
close #91 
- ヒアドキュメント受け取り中にCtrl + C押されたときに動くシグナルハンドラーを作成しました。
- test/test.shを追加しました
- norm3.3.2にしたらエラー出てきたところ(srcs/tokenize1.c)を修正しました。
=> add : heredoc signal_handler

srcs/command_builtin1.c, srcs/execution_utils.c, srcs/setdata_cmdline_redirection.c
=> support norm 3.3.2

srcs/command_builtin1.c
=> mod builtin_cd()

srcs/setdata_heredoc_cmdtype.c
is_quotをフラグとして扱うための=0で初期化作業の場所を修正しました。
=> mod heredoc() is_quot

test/test_main.c
テストの時のmain関数をtestディレクトリに入れさせてもらいました。
=> add test_main

includes/parse.h, srcs/expansion_cmdlist.c, srcs/parse_cmd.c, srcs/tokenize1.c, test/cmdline.txt, test/test.sh
```diff
- void		serch_env_cmdlist(t_cmdlist **clist, t_envlist *envlist);
+ void		expand_cmdlist(t_cmdlist **clist, t_envlist *envlist);
- t_token		*tokenize_cmd_by_space(char *cmd, bool *err);
+ t_token		*tokenize_cmd(char *cmd, bool *err);
- static void	serch_new_space_cmdlist(t_cmdlist *clist)
+ static void	search_new_space_cmdlist(t_cmdlist *clist)
```
- test/cmdline.txtにテストケース追加しました。
- なぜか前プッシュした内容も反映されてます。
=> 関数名ちょい変えました

srcs/tokenize2.c, test/test.sh
=> M	srcs/tokenize2.c

.gitignore, srcs/expansion_cmdlist.c
llvmバージョンアップしたら不使用関数が検出されたので直しました。
=> rm: unused val
